In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
print(x)
print(type(x))
y=[1,2,3,4]
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


In [ ]:
l=[]
for i in range(1,5):
  int_l=int(input('enter:'))
  l.append(int_l)

x=np.array(l)
print(x)


enter:10
enter:20
enter:30
enter:40
[10 20 30 40]


In [ ]:
ar2=np.array([[1,2,3,4],[1,2,3,4,]])
print(ar2)
print(ar2.ndim)

ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)


[[1 2 3 4]
 [1 2 3 4]]
2
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
ar4=np.array([1,2,3],ndmin=3)
print(ar4)
print(ar4.ndim)

[[[1 2 3]]]
3


# **Creatng NumPy Arrays using functions**

# **Zeros**

In [ ]:
ar_zero=np.zeros(4)
print(ar_zero)
print()

ar_zero1=np.zeros((3,4))
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# **Ones**

In [ ]:
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# **Range**

In [ ]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


# **linspace**

In [ ]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# **Diagonal**

In [ ]:
ar_dia=np.eye(5,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# **Creating Arrays using Random Numbers**

In [ ]:
var = np.random.rand(4) # close to 1
print(var)
print()
var1 = np.random.rand(2,5)
print(var1)

[0.54530938 0.32333198 0.79345131 0.08374944]

[[0.79014197 0.23192541 0.75542653 0.24410153 0.20492416]
 [0.93179549 0.37359728 0.84251909 0.25830765 0.65462906]]


In [ ]:
var = np.random.randn(4)  # close to 1 but also include negative values
print(var)

[-0.06282611 -1.48015586  0.43751195  1.32067119]


In [ ]:
var3 = np.random.randint(5,20,5)
print(var3)

[14  6 14 19 19]


In [ ]:
var= np.array([1,2,3,4])
varadd=var + 3
print(varadd)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd=var1 + var2
print(varadd)


[2 4 6 8]


In [ ]:
var= np.array([1,2,3,4])
varadd=var * 3
print(varadd)

[ 1  8 27 64]


In [ ]:
ar1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd=var1 * var2
print(varadd)

[ 1  4  9 16]


In [ ]:
var= np.array([1,2,3,4])
varadd=var / 3
print(varadd)


[0.33333333 0.66666667 1.         1.33333333]


# **2D Array**

In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[10,20,30,40],[100,200,300,400]])

print(var21)
print()
print(var22)
print()

# varadd2=var21 + var22
varadd2=np.add(var21,var22)
print(varadd2)


[[1 2 3 4]
 [1 2 3 4]]

[[ 10  20  30  40]
 [100 200 300 400]]

[[ 11  22  33  44]
 [101 202 303 404]]


In [ ]:
var =np.array([3,2,1,4,5,3,2])
print('min:',np.min(var),np.argmin(var))
print('max:',np.max(var),np.argmax(var))


min: 1 2
max: 5 4


In [ ]:
var1 = np.array([[3,1,2],[9,5,6],[8,1,3],[7,1,3]])
print(np.min(var1,axis=1)) # axis=0 refers cols, 1 is rows

[1 5 1 1]


In [ ]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))


[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [ ]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [ ]:
var = np.array([1,2,3,4],ndmin=4)
print(var)
print()
print(var.shape)

[[[[1 2 3 4]]]]

(1, 1, 1, 4)


# **ReShape**

In [ ]:
var2=np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x=var2.reshape(2,3)

print(x)
print(x.ndim)


[1 2 3 4 5 6]
1

[[1 2 3]
 [4 5 6]]
2


In [ ]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)

print()

x=var2.reshape(2,3,2)

print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


# **BroadCasting Arrays**

In [ ]:
var1=np.array([1,2,3])
print(var1)
print()

var2=np.array([[1],[2],[3]])
print(var2)
print()

print(var1 + var2)


[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
x=np.array([[1],[2]])
print(x.shape)

y=np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


# **Indexing**

In [ ]:
var =np.array([9,8,7,6])
            # 0,1,2,3
            # -4,-3,-2,-1
print(var[1])
print(var[-3])

8
8


In [ ]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1[0,1])

8


In [ ]:
var1 = np.array([[[1,2],[6,7]]])

print(var1[0,1,1])

7


# **Slicing**

In [ ]:
var = np.array([9,8,7,6,5,4,3])

print(var[1:5])
print(var[1:])
print(var[:5])

[8 7 6 5]
[8 7 6 5 4 3]
[9 8 7 6 5]


In [ ]:
var = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var)
print()

print(var[1,1:])


[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

[8 7 6 5]


# **Copy vs View**

In [8]:
import numpy as np

var = np.array([1,2,3,4])
cp=var.copy()

print("var:",var)
print("copy:",cp)
print(id(var))
print(id(cp))
var[1]=8
print("var:",var)
print("copy:",cp)


var: [1 2 3 4]
copy: [1 2 3 4]
133346544336208
133346544204656
var: [1 8 3 4]
copy: [1 2 3 4]


In [6]:
x=np.array([9,8,7,6,5])
vi=x.view()
print("x:",x)
print("view:",vi)
print(id(x))
print(id(vi))

x: [9 8 7 6 5]
view: [9 8 7 6 5]
133346544321520
133346544322000


In [7]:
x[1]=40
print("x:",x)
print("view:",vi)

x: [ 9 40  7  6  5]
view: [ 9 40  7  6  5]


In [11]:
# Joining of Arrays: putting content of two or more arrays in a single array
var1=np.array([[1,2],[3,4]])
var2=np.array([[9,8],[7,6]])

ar_new = np.concatenate((var1,var2),axis=0)
print(var1)
print()
print(var2)
print()
print(ar_new)




[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [13]:
#Stack Function (Merging Arrays)
var1=np.array([1,2,3,4])
var2=np.array([9,8,7,6])

a_new=np.stack((var1,var2),axis=0)
print(a_new)


[[1 2 3 4]
 [9 8 7 6]]


In [14]:
var1=np.array([1,2,3,4])
var2=np.array([9,8,7,6])

a_new=np.vstack((var1,var2))
print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [16]:
var1=np.array([1,2,3,4])
var2=np.array([9,8,7,6])

a_new=np.hstack((var1,var2))
print(a_new)

[1 2 3 4 9 8 7 6]


In [18]:
#Split arrays : breaks one array into multiple arrays
var= np.array([1,2,3,4,5,6])
print(var)

ar=np.array_split(var,3)
print()
print(ar)
print(ar[0])


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [19]:
var1= np.array([[1,2],[3,4],[5,6]])
print(var1)

ar1=np.array_split(var1,3)
print()
print(ar1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# **Search Array**

In [22]:
var=np.array([1,2,3,4,5,2,5,2,6,7])

x=np.where((var%2)==0)
print(x)

(array([1, 3, 5, 7, 8]),)


In [23]:
# Sort the array
var=np.array([1,2,3,4,5,2,5,2,6,7])
print(np.sort(var))

[1 2 2 2 3 4 5 5 6 7]


In [24]:
var

array([1, 2, 3, 4, 5, 2, 5, 2, 6, 7])

# **Insert**

In [25]:
var =np.array([1,2,3,4])
print(var)

v=np.insert(var,2,40)

print(v)


[1 2 3 4]
[ 1  2 40  3  4]


In [26]:
var =np.array([1,2,3,4])
print(var)

v=np.insert(var,(2,4),40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [27]:
var1 =np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6,axis=0)
print(v1)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [28]:
var1 =np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6,axis=1)
print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [29]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.append(var1,[[45,44,33]],axis=0)
print(v1)


[[ 1  2  3]
 [ 1  2  3]
 [45 44 33]]


In [32]:
var1=np.array([1,2,3,4])
v1=np.append(var1,6)
print(v1)

[1 2 3 4 6]


In [33]:
# Delete
var1=np.array([1,2,3,4])
print(var1)
d=np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]
