In [ ]:
import sys

In [ ]:
myname='Ramnath'
a_num=12
print(type(myname))
print(type(a_num))
a_num='hello'
print(type(a_num))

<class 'str'>
<class 'int'>
<class 'str'>


In [ ]:
n1=123
print(n1)
print(id(n1))
# n2=200
n2=n1
print(n2)
print(id(n2))


123
11645992
123
11645992


In [ ]:
n1='Raman'
print('value of n1 is ',n1)

value of n1 is  Raman


In [ ]:
n1=input('enter a name:')
print(n1)
type(n1)

enter a name:John
John


str

In [ ]:
n1*10

1000

In [ ]:
n1**2

10000

In [ ]:
n1**12

1000000000000000000000000

In [ ]:
n1**124

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [ ]:
n1=12.14
type(n1)

float

In [ ]:
n1=10
print(n1/10)

1.0


In [ ]:
n1=13
n1/2

6.5

In [ ]:
n1//2

6

In [ ]:
n1%2

1

In [ ]:
n1=input('enter any number:')
n1=int(n1)
type(n1)

enter any number:20


int

In [ ]:
name='Ramnath'
name2="Ramnath"
print(id(name))
print(id(name2))

138932606590416
138932606590416


In [ ]:
name3="Alfred D'Souza"
name3

"Alfred D'Souza"

In [ ]:
name='ramnath'
name.upper()
name.isnumeric()
name='100'
name.isnumeric()

True

In [ ]:
cities="bangalore,mysore,mumbai,delhi"
splitted=cities.split(',')
print(splitted)
joined=','.join(splitted)
print(joined)


['bangalore', 'mysore', 'mumbai', 'delhi']
bangalore,mysore,mumbai,delhi


In [ ]:
delimeter='#'
delimeter.join(['bangalore', 'mysore', 'mumbai', 'delhi'])


'bangalore#mysore#mumbai#delhi'

**Boolean Values: 'True' or 'False'**
Note: true is not same as True in python. true will be treated as a variable not boolean value

In [ ]:
print(True)

True


In [ ]:
print(true)

NameError: name 'true' is not defined

Arithmatic Operators : +,-,*,/,//,%
Relational operators: <,<=,>,>=,==,!=

**Logical operators:  and, or , not**

## **Control flow statements**
Note: after : , next line must have indention to make it as block

In [ ]:
num=int(input('Enter a number:'))
if num>1000:
  print('Hey, you hae eneterd a big number')
  print('-'*50)
print('done')

Enter a number:500
done


In [ ]:
num=int(input('Enter a number:'))
if num % 2 ==0:
  print('It is an even number')
else:
  print('It is an odd number')

print('finished')

Enter a number:6
It is an even number
finished


In [ ]:
month=int(input('Enter a month(1-12):'))
if month<1 or month>12:
  print('You have eneterd an invalid number for a month')
else:
  if month==2:
    print('There are either 28 or 29 days in this month')
  elif month in (4,6,9,11):
    print('There are 30 days in this month')
  else:
    print('There are 31 days in this month')




Enter a month(1-12):4
There are 30 days in this month


In [ ]:
name=input('Enter a name:')
age=int(input('Enter the age:'))
person_type='minor' if age<18 else 'adult'
print('%s is a %s' % (name,person_type ))

Enter a name:Ravi
Enter the age:25
Ravi is a adult


### **Using while loop**

In [ ]:
num=int(input('Enter a number:'))
limit=int(input('Enter the limit:'))
i=1
while i<=limit:
  print('{} X {} = {}'.format(num,i,num*i))
  i+=1

print('Done')

Enter a number:5
Enter the limit:10
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
Done


In [ ]:
from re import I
num=int(input('Enter a number:'))
i=1
f=1
while i<=num:
  f=f*i
  i+=1

print('Factorial of %d is %d' %(num,f))

Enter a number:5
Factorial of 5 is 120


**For Loop**

In [ ]:
for name in ('ram','shyam','john','jane'):
  print(name)

print()

for num in (1,2,3,4,5,6,7,8,9,10):
  print(num)

print()

for num in range(10):
  print(num)   # will display 0 to 9, not 10

print()

for num in range(1,10):
  print(num)   # will display 1 to 9, not 10

print()
for num in range(1,10,2):
  print(num)   # will display 1,3,... to 9, skip by 1


ram
shyam
john
jane

1
2
3
4
5
6
7
8
9
10

0
1
2
3
4
5
6
7
8
9

1
2
3
4
5
6
7
8
9

1
3
5
7
9


# **User-Defined Functions**

In [ ]:
def is_leap(year):
  return year%400 or (year%4 and year%100!=0)

num=int(input('Enter an year:'))
if is_leap(num):
  print('There are 366 days in the input year')
else:
  print('There are 365 days in the input year')

Enter an year:2024
There are 366 days in the input year


In [ ]:
def max_days_in_month(month,year):
  if month<1 or month>12:
    raise Exception('Invalid month; must be between 1 and 12')
  if month==2:
    return 29 if is_leap(year) else 28
  elif month in (4,6,9,11):
    return 30
  else:
    return 31

def main():
  m=int(input('Enter month:'))
  y=int(input('Enter year:'))
  days=max_days_in_month(m,y)
  print('There are %d days in the month/year %d/%d' % (days,m,y))


main()

Enter month:5
Enter year:2025
There are 31 days in the month/year 5/2025


# **Parameters and return values in a function:**

In [ ]:
def greet(name='friend',city='Bangalore'):   # default values of the parameters
  print('Hello %s, how is the weather in %s?' %(name,city))

def main():
  name=input('Enter your name:')
  city=input('Where are you from?:')

  message=greet(name,city)
  print('message is',message)


greet('Ramnath')
greet()

#main()


Hello Ramnath, how is the weather in Bangalore?
Hello friend, how is the weather in Bangalore?


In [ ]:
def factorial(n):
  if n<=1: return 1
  return n*factorial(n-1)

num=5
f=factorial(num)
print('Factorial of %d is %d'%(num,f))

Factorial of 5 is 120


# **Collections in Python**
**A colectionn is an object that contains multiple other objetcs. In Python there are 4 types of collections**

-List

-Tuple

-Set

-Dict


# **1. List:**

In [ ]:
l1=[]
print(type(l1))

l2=list()
print(type(l2))

l1=['ramnath','hema','yash','vaibhav']
print(l1)

l2=list(['ramnath', 'hema', 'yash', 'vaibhav'])
print(type(l2))

print(l1[0])
print(l1[-1])


<class 'list'>
<class 'list'>
['ramnath', 'hema', 'yash', 'vaibhav']
<class 'list'>
ramnath
vaibhav


In [ ]:
l2+=['john','dave']
print(l2)

['ramnath', 'hema', 'yash', 'vaibhav', 'john', 'dave']


In [ ]:
l2+='Iyan'
print(l2)

['ramnath', 'hema', 'yash', 'vaibhav', 'john', 'dave', 'r', 'o', 'b', 'e', 'r', 't', 'robert', 'I', 'y', 'a', 'n']


In [ ]:
l2=list(['ramnath', 'hema', 'yash', 'vaibhav'])
# l2.append(['tom','myora'])
# l2.extend(['rakesh','suresh'])
print(l2)
l2.insert(4,'abc')
#print(l2.index(['tom','myora']))
print(l2)
l2.reverse()
print(l2)
l2.sort()
print(l2)



['ramnath', 'hema', 'yash', 'vaibhav']
['ramnath', 'hema', 'yash', 'vaibhav', 'abc']
['abc', 'vaibhav', 'yash', 'hema', 'ramnath']
['abc', 'hema', 'ramnath', 'vaibhav', 'yash']


In [ ]:
l2=list(['ramnath', 'hema', 'yash', 'vaibhav'])
l3=l2.copy()  # shallow copy, it will create altogether another list

l3+=['john']

print(l2)
print(l3)

['ramnath', 'hema', 'yash', 'vaibhav']
['ramnath', 'hema', 'yash', 'vaibhav', 'john']


In [ ]:
l2=list(['ramnath', 'hema', 'yash', 'vaibhav','john'])
for n in l2: print(n)

ramnath
hema
yash
vaibhav
john


# **Slice**

In [ ]:
print(l2[1:])
print(l2[:3])
print(l2[0:4:2])
print(l2[::2])
print(l2[::])

['hema', 'yash', 'vaibhav', 'john']
['ramnath', 'hema', 'yash']
['ramnath', 'yash']
['ramnath', 'yash', 'john']
['ramnath', 'hema', 'yash', 'vaibhav', 'john']


In [ ]:
l2[2]='rohit'
print(l2)

#l2[2:4]='jack'
#print(l2)

l2[2:]='vinay'
print(l2)


['ramnath', 'hema', 'rohit', 'vaibhav', 'john']
['ramnath', 'hema', 'v', 'i', 'n', 'a', 'y']


# **Tuple** : It is a read-only collection.

In [ ]:
names=('ramnath','rohit')
print('before:',id(names))
print(type(names))
print(names[0])
print(names[-1])
# names[0]='David' --invalid

names+=('john','tom')
print(names)
print('after:',id(names))


before: 138932259283648
<class 'tuple'>
ramnath
rohit
('ramnath', 'rohit', 'john', 'tom')
after: 138932262530688


In [ ]:
names=tuple(['ravi','rohit'])
print(names)
print(type(names))

('ravi', 'rohit')
<class 'tuple'>


In [ ]:
import numpy as np

A = np.array([[1],
              [2],
              [3]])    # shape (3,1)

B = np.array([10, 20, 30, 40])   # shape (4,)

C = A + B
print(C)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


## **Set** : A Set is a collection of unique values so without any repetition

- we use {} to create a set but if we use empty {} then it will create 'dict' short form of dictionary.

In [ ]:
set1={} # creates dictionary if empty not Set
print(type(set1))

set2={10,20,30,40,50,40,30,50,90}
print(type(set2))
print(set2)

names={'ramnath','yash','vaibhav','yash','rohit'}
# print(names[0])   does not support index based access

for n in names:   # access only using loop
  print(n)

# unlike tuple, the set is not immutable, we can add or delete the values and so on.

dir(set2)


<class 'dict'>
<class 'set'>
{50, 20, 90, 40, 10, 30}
rohit
vaibhav
ramnath
yash


['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
set1={1,2,3,4}
set2=set1.copy()

print(id(set1))
print(id(set2))


136113597734848
136113597738432


In [ ]:
# all the methods are given as per the set operatios
n1={1,2,3,4,5}
n2={4,5,6,7}
print('n1:',n1)
print('n2:',n2)
print('n1.difference(n2):',n1.difference(n2))
print('n1:',n1)
print('n1-n2:',n1-n2)
print('n2.difference(n1):',n2.difference(n1))
print('n2-n1:',n2-n1)

n1: {1, 2, 3, 4, 5}
n2: {4, 5, 6, 7}
n1.difference(n2): {1, 2, 3}
n1: {1, 2, 3, 4, 5}
n1-n2: {1, 2, 3}
n2.difference(n1): {6, 7}
n2-n1: {6, 7}


In [ ]:
n1={1,2,3,4,5}
n2={4,5,6,7}
print('n1:',n1)
print('n2:',n2)
n1.difference_update(n2)
print('n1:',n1)

n1: {1, 2, 3, 4, 5}
n2: {4, 5, 6, 7}
n1: {1, 2, 3}


In [ ]:
n1={1,2,3,4,5}
n2={4,5,6,7}
print('n1:',n1)
print('n2:',n2)

print('union:',n1.union(n2))
print('n1|n2:',n1|n2)

n1: {1, 2, 3, 4, 5}
n2: {4, 5, 6, 7}
union: {1, 2, 3, 4, 5, 6, 7}
n1|n2: {1, 2, 3, 4, 5, 6, 7}


In [ ]:
n1={1,2,3,4,5}
n2={4,5,6,7}
print('n1:',n1)
print('n2:',n2)
print('n1.intersection(n2):',n1.intersection(n2))
print('n1=n2:',n1&n2)
print(n1)
n1.intersection_update(n2)
print(n1)
print(len(n1))

n1: {1, 2, 3, 4, 5}
n2: {4, 5, 6, 7}
n1.intersection(n2): {4, 5}
n1=n2: {4, 5}
{1, 2, 3, 4, 5}
{4, 5}
2


# **Dictionary:** : it stores and access value as key/value pairs

In [ ]:
book={1001:"Python Basics",1002:"Numpy Library",1003:'Pandas'}
print(book[1003])


Pandas
